---
title: "Predicting Credit Card Default Rates"
output:
  html_document: default
  pdf_document: default
---

## Introduction to the data

In this example, we will explore a data set that contains information on default payments, demographic factors, credit data, history of payment, and bill statements of credit card clients in Taiwan from April 2005 to September 2005.

This data set was obtained from the University of California, Irvine archives.

Source: <https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients>

## Exploring the Data

First, Let us load the data into R and take an initial look at what we are dealing with. the str() function will allow us to compactly display the internal structure of our data set "credit1". the summary() function will allow us to view a statistical summary of each of the variables we are dealing with.

```{r}
credit1 = read.csv("creditcard.csv")
str(credit1)
summary(credit1)
```

The next step is to find out if we have any missing value, or if we will need to preform other types of data management.

```{R}
library(dplyr)
missing = credit1 %>% summarise_all(funs(sum(is.na(.))/n()))
missing
# Lets remove the ID variable it is not needed
credit=credit1[,-1]
```

### Data Visualizations

Now lets create some data visualizations to learn more about the data. The first visualization will look at the percentage of clients who have not defaulted vs the those who have defaulted.

```{R}
library(ggplot2)
credit %>% 
  group_by(default.payment.next.month) %>% 
  summarise(Count = n())%>% 
  mutate(percent = prop.table(Count)*100)%>%
  ggplot(aes(reorder(default.payment.next.month, -percent), percent), fill = default.payment.next.month)+
  geom_col(fill = c("grey", "light blue"))+
  geom_text(aes(label = sprintf("%.1f%%", percent)), hjust = 0.2, vjust = 2, size = 5)+ 
  theme_bw()+  
  xlab("Default (0:No, 1:Yes)") + ylab("Percent") + ggtitle("Default Percent")
```

We see that 22.1% of clients have defaulted on their monthly payment and 77.9% of clients have not.

Visuals Continued

```{R}
library(ggplot2)
ggplot(credit, aes(x = LIMIT_BAL)) + geom_histogram()
ggplot(credit, aes(x = SEX)) + geom_histogram()
ggplot(credit, aes(x = EDUCATION)) + geom_histogram()
ggplot(credit, aes(x = MARRIAGE)) + geom_histogram()
ggplot(credit, aes(x = AGE)) + geom_histogram()
ggplot(credit, aes(x = PAY_0)) + geom_histogram()
ggplot(credit, aes(x = PAY_2)) + geom_histogram()
table(credit$PAY_0)
```

Limit_bal histogram - shows us the number of clients with a given credit balance in Taiwan Dollars. We can see that there is a large amount of clients with lower credit balances and a lower number of clients with higher credit amounts.

Age histogram - Shows us the number of credit card clients by age. We can see that the majority of clients are younger than 40 years of age.

### Data Management

Here we will preform some data management by combining variables that have a low number of observations with other variables that have low numbers of observations. We will also create some visuals for the new combined variables as well as turn some numeric variables into factors. This is so that we are able to run our logistical regression in the next steps.

```{R}
# There are some catergories with very few observations. Let's group them together.
credit$EDUCATION[credit$EDUCATION == 0] = 4
credit$EDUCATION[credit$EDUCATION == 5] = 4
credit$EDUCATION[credit$EDUCATION == 6] = 4
credit$MARRIAGE[credit$MARRIAGE == 0] = 3

ggplot(credit, aes(x = EDUCATION)) + geom_histogram()
ggplot(credit, aes(x = MARRIAGE)) + geom_histogram()

# Make some numeric variables into factors
credit$default.payment.next.month=as.factor(credit$default.payment.next.month)
credit$SEX=as.factor(credit$SEX) 
credit$EDUCATION=as.factor(credit$EDUCATION)
credit$MARRIAGE=as.factor(credit$MARRIAGE)
```

### Exploratory Data Analysis

Let us explore our data a little bit more. In this section we will run some simple EDA "Exploratory Data Analysis" by using ggplot to create some bar charts, box plot, and violin charts. This will help us better understand our data.

```{R}
# Some simple EDA
# Default against catergorial variables
ggplot(credit, aes(x=SEX,fill=default.payment.next.month))+ geom_bar()+ theme_bw() 
ggplot(credit, aes(x=EDUCATION,fill=default.payment.next.month))+ geom_bar()+theme_bw()
ggplot(credit, aes(x=MARRIAGE,fill=default.payment.next.month))+ geom_bar()+theme_bw()

# Default against numeric variables
ggplot(credit, aes(x=default.payment.next.month, y=LIMIT_BAL, fill=default.payment.next.month)) + geom_violin()+
  geom_boxplot(width=0.1, fill="white") + labs(title="Amount of given credit in NT dollars")
ggplot(credit, aes(x=default.payment.next.month, y=AGE, fill=default.payment.next.month)) + geom_violin()+
  geom_boxplot(width=0.1, fill="white") + labs(title="Age")
ggplot(credit, aes(x=default.payment.next.month, y=PAY_0, fill=default.payment.next.month)) + geom_violin()+
  geom_boxplot(width=0.1, fill="white") + labs(title="Repayment status in September, 2005")
ggplot(credit, aes(x=default.payment.next.month, y=BILL_AMT1, fill=default.payment.next.month)) + geom_violin()+
  geom_boxplot(width=0.1, fill="white") + labs(title="Amount of bill statement in September, 2005 (NT dollar)")+
  ylim(0,125000)
ggplot(credit, aes(x=default.payment.next.month, y=PAY_AMT1, fill=default.payment.next.month)) + geom_violin()+
  geom_boxplot(width=0.1, fill="white") + labs(title="Amount of previous payment in September, 2005 (NT dollar)")+
  ylim(0,10000)
```

In the bar charts there are two components the first being the variable that we are observing which is on the X - axis, and the second is if the client defaulted on their monthly payment where the salmon color means no, and the blue means yes.

If we take a look at the education bar chart where, 1 = graduate school, 2 = university, 3 = high school, and 4 = other. We can see that the majority of the credit card clients have a university degree or higher. We can also see the split between clients who did not default on their payment an clients who did default on their payment relative to the category the client falls under.

If we look at the violin and box charts. The first thing we notice is that we have separated the clients who have defaulted on their credit card payment from those who did not. We did this to compare the two groups to each other.

In the violin and box charts, like the bar charts, are made up of multiple components. This time our variable we are observing is on the Y - axis. The first part of our visual insights is the violin, or blob looking portion of the chart. This part of the chart allows us to see the density of observations as we move up from 0. The wider the blob the greater the number of observations, the narrower the blob the lesser the number of observations. The second part, is the box plot which allows us to see the median, upper quartile, lower quartile, and both upper and lower extremes. The last part is if the client defaulted on their monthly payment where the salmon color means no, and the blue means yes.

Lets take a look at the characteristics of the clients who did not default on their payment compared to those of the clients who did using our limit_bal variable. The first thing to make note of is that the group that defaulted has a wider base, letting us know that there was a large amount of clients who defaulted with lower credit limits available to them. The second thing we notice is that the group that did not default has more clients with larger credit limits and an outlier with a really high credit limit compared to the default group. 

### The Logistical Regression

Now we will run a logistical regression

```{R}
# Logistic model
logit.1 = glm(default.payment.next.month~., data=credit, family="binomial")
summary(logit.1)
```

### Predicting Credit Default Rates

```{R}
pred = predict(logit.1, type = "response", credit)
summary(pred)

str(pred)
```
